config/routes.rb
Rails.application.routes.draw do
  resources :companies do
    collection { post :import }
  end

  devise_for :users
  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/faq'
  get 'welcome/pricing'
  get 'welcome/features'
  
  resources :invoices
  
  root to: 'welcome#index'
  


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Company.create! row.to_hash
    end
  end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |company|
        csv << company.attributes.values_at(*column_names)
      end
    end
  end


end

app/models/invoice.rb
# frozen_string_literal: true

class Invoice < ApplicationRecord

end

app/models/invoice_search.rb
# frozen_string_literal: true

class InvoiceSearch

  # This is a class

  attr_reader :date_from, :date_to

  def initialize(params)
    params ||={}
    @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
  end

  def scope
    Invoice.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end

  private

  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]

  # GET /companies or /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html
      format.csv { send_data @companies.to_csv}
    end
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies or /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: "Company was successfully created." }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1 or /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: "Company was successfully updated." }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1 or /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: "Company was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def import
    Company.import(params[:file])
    redirect_to companies_path, notice: "Companies Added Succsessfully"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :manager, :status, :terms)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action :set_invoice, only: %i[show edit update destroy]

  # GET /invoices or /invoices.json
  def index
    @search = InvoiceSearch.new(params[:search])
    @invoices = @search.scope
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def invoice_params
    params.require(:invoice).permit(:date, :company, :tax, :salesperson)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def faq
  end

  def pricing
  end

  def features
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



   end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :manager %>
    <%= form.text_field :manager %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :terms %>
    <%= form.number_field :terms %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing Companies</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Manager</th>
            <th>Status</th>
            <th>Terms</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @companies.each do |company| %>
            <tr>
              <td><%= company.name %></td>
              <td><%= company.manager %></td>
              <td><%= company.status %></td>
              <td><%= company.terms %></td>
              <td><%= link_to 'Show', company, class: 'btn btn-secondary btn-sm' %></td>
              <td><%= link_to 'Edit', edit_company_path(company), class: 'btn btn-sm btn-warning' %></td>
              <td><%= link_to 'Destroy', company, method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<br/>
<%= link_to 'New Company', new_company_path, class: 'btn btn-success' %>
<br>
<br>
<h3>Import Companies</h3>

<%= form_tag import_companies_path, multipart: true do %>
  <%=file_field_tag :file, style: 'margin-right: 50px;' %>
  
  <%=submit_tag "Upload Companies", class: 'btn btn-warning' %>
<% end %>
<br/>
<br/>
<h3>Download File</h3>
<%=link_to "Report", companies_path(format: "csv"), class: 'btn btn-primary' %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @company.manager %>
</p>

<p>
  <strong>Status:</strong>
  <%= @company.status %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @company.terms %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/invoices/_form.html.erb
<div class="">
  <%= form_with(model: invoice) do |form| %>
    <% if invoice.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

        <ul>
          <% invoice.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="">
      <div class="field">
        <%= form.label :date %>
        <%= form.datetime_select :date %>
      </div>

      <div class="field">
        <%= form.label :company %>
        <%= form.text_field :company %>
      </div>

      <div class="field">
        <%= form.label :tax %>
        <%= form.text_field :tax %>
      </div>

      <div class="field">
        <%= form.label :salesperson %>
        <%= form.text_field :salesperson %>
      </div>
    </div>
      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>

</div>

app/views/invoices/edit.html.erb
<div class="container">
  <h1>Editing Invoice</h1>


  <%= render 'form', invoice: @invoice %>

  <%= link_to 'Show', @invoice %> |
  <%= link_to 'Back', invoices_path %>
</div>

app/views/invoices/index.html.erb
<div class="row">
  <h1>Listing Invoices</h1>
  <div class="pull-right range-query">
    <%= form_tag invoices_path, method: :get do %>
      <%= text_field_tag 'search[date_from]', @search.date_from %>
      <%= text_field_tag 'search[date_to]', @search.date_to %>
      <%= submit_tag 'Search', class: 'btn btn-sm btn-success' %>
    <%end%>
  </div>
</div>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Company</th>
          <th>Tax</th>
          <th>Salesperson</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @invoices.each do |invoice| %>
          <tr>
            <td><%= invoice.date.strftime("%Y/%m/%d") %></td>
            <td><%= invoice.company %></td>
            <td><%= invoice.tax %></td>
            <td><%= invoice.salesperson %></td>
            <td><%= link_to 'Show', invoice, class: 'btn btn-secondary btn-sm' %></td>
            <td><%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-sm btn-success' %></td>
            <td><%= link_to 'Destroy', invoice, method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

<%= link_to 'New Invoice', new_invoice_path, class: 'btn btn-primary' %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @invoice.date %>
</p>

<p>
  <strong>Company:</strong>
  <%= @invoice.company %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @invoice.tax %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @invoice.salesperson %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnterpriseAPE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
<body>
<div class="container">
  <ul class="nav nav-tabs link-hover justify-content-center">  
    <li class = "nav-link active"><%= link_to "Home", root_path %>                   </li>
    <li class = "nav-link"><%= link_to "About Us", welcome_about_path %>      </li>
    <li class = "nav-link"><%= link_to "Contact", welcome_contact_path %>     </li>
    <li class = "nav-link"><%= link_to "Features", welcome_features_path %>   </li>
    <li class = "nav-link"><%= link_to "FAQs", welcome_faq_path %>            </li>
    <li class = "nav-link"><%= link_to "Pricing", welcome_pricing_path %>     </li>
    <li class = "nav-link"><%= link_to "Invoices", invoices_path %>           </li>

    <% if current_user %>
      <li class = "nav-link"><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %> </li>
    <% else %>
      <li class = "nav-link"><%= link_to "Sign Up", new_user_registration_path %>
      <li class = "nav-link"><%= link_to "Sign In", new_user_session_path %>
    <% end %>
  </ul> 
</div>  
  
  <div class="container">
  <br/>
   <% if flash[:notice] %>
     <div class="alert alert-success" role="alert">
       <button type="button" class="close" data-bs-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>

  <% elsif flash[:error] %>
    <div class="alert alert-danger" role="alert">
      <button type="button" class="close" data-bs-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>

  <% elsif flash[:alert] %>
    <div class="alert alert-warning" role="alert">
      <button type="button" class="close" data-bs-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>

  <% end %>

  <br/>

  <%= yield %>

  </div>
  
</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in this location app/views/welcome/about.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/faq.html.erb
<h1>Welcome#faq</h1>
<p>Find me in app/views/welcome/faq.html.erb</p>

app/views/welcome/features.html.erb
<h1>Welcome#features</h1>
<p>Find me in app/views/welcome/features.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/pricing.html.erb
<h1>Welcome#pricing</h1>
<p>Find me in app/views/welcome/pricing.html.erb</p>